version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_NAME=data-syn-poc-ecr-group-1
      - REPOSITORY_URI=456686683148.dkr.ecr.eu-west-1.amazonaws.com/data-syn-poc-ecr-group-1
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build commands
      - echo Build started on `date`
      - echo Building the Docker image...
      - chmod +x docker && cd docker
      
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      - cd ..
  post_build:
    commands:
      - echo Updating ECS Service
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      
      # Run script to update task definition & service
      - pwd
      - ls -l
      - ./ecs-deploy.sh $REPOSITORY_URI:$IMAGE_TAG
      - echo ECS Update Service has been completed
      # insert pre-built validation scripts here
      # python validation.py



